// src/app/layout.tsx

import localFont from "next/font/local";

import ClientLayout from "@/components/ClientLayout";

import type { Metadata, Viewport } from "next";
import "../styles/globals.css";
import "../styles/line-colors.css";

const seoulAlrim = localFont({
	src: "../assets/fonts/SeoulAlrim-Medium.otf",
	variable: "--font-seoul-alrim",
});

export const metadata: Metadata = {
	title: "Commuter",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	viewportFit: "cover",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${seoulAlrim.variable} bg-white antialiased`}>
				<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	);
}
