// src/app/layout.tsx

import localFont from "next/font/local";

import Header from "@/components/@common/Header";
import TabBar from "@/components/@common/TabBar";

import type { Metadata, Viewport } from "next";
import "../styles/globals.css";

const seoulAlrim = localFont({
	src: "../assets/fonts/SeoulAlrim-Medium.otf",
	variable: "--font-seoul-alrim",
});

export const metadata: Metadata = {
	title: "Commuter",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	viewportFit: "cover",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${seoulAlrim.variable} flex w-full max-w-[400px] items-center justify-around bg-white antialiased`}
			>
				<Header />
				{/* Header, TabBar 클래스(h-숫자) 변경에 따라 메인 레이아웃 mt(헤더), mb(탭바) 크기 변경 필요 */}
				<main className="relative mt-12 mb-16 min-h-screen w-full max-w-[400px] px-4 py-4">
					{children}
				</main>
				<TabBar />
			</body>
		</html>
	);
}
