#!/usr/bin/env sh
echo "🔍 commit 이전에 lint 규칙과 prettier를 적용합니다..."

if npx lint-staged; then
  echo "🌟 모든 ESlint 및 Prettier 규칙이 성공적으로 적용되었습니다."
else
  echo "❌ 검사에서 오류가 발생했습니다. 자세한 내용은 위 로그를 확인하세요."
  exit 1
fi