name: pull-request-support

on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      pull-requests: write
      issues: write # required for auto-assign feature
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" # required
          branch-prefix: "/" # required
          resolve: true # optional, default: false
