name: PR Review Notification

on:
  pull_request:
    types: [opened, ready_for_review, reopened] # PR이 열리거나 '리뷰 준비' 상태가 될 때 실행
jobs:
  assign-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        id: assign_reviewer
        uses: pull-request-assigner/github-action@v6.2.0
        with:
          # PR을 생성한 사람은 자동으로 제외
          assignees: |
            subin4420
            s-eun20
            minjeongj0
            yesslee
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Map GitHub username to Slack ID
        id: get_slack_id
        if: steps.assign_reviewer.outputs.assignees_json != '[]' # 리뷰어가 할당된 경우에만 실행
        run: |
          REVIEWER_GH_USERNAME=$(echo '${{ steps.assign_reviewer.outputs.assignees_json }}' | jq -r '.[0]')
          echo "Assigned reviewer: $REVIEWER_GH_USERNAME"

          USER_MAP=$(cat <<-EOF
          {
            "subin4420": "U098VUTEBU4",
            "s-eun20": "U099N6W3K40",
            "minjeongj0": "U0991TXEKDJ",
            "yesslee": "U098R2VUC11"
          }
          EOF
          )

          SLACK_USER_ID=$(echo "$USER_MAP" | jq -r --arg REVIEWER "$REVIEWER_GH_USERNAME" '.[$REVIEWER]')
          echo "slack_id=$SLACK_USER_ID" >> "$GITHUB_OUTPUT"

      - name: Send Slack Notification
        if: steps.get_slack_id.outputs.slack_id != '' # 리뷰어가 할당된 경우에만 실행
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "C09JB820MFF" # 알림을 보낼 채널 ID
          slack-message: |
            "<@${{ steps.get_slack_id.outputs.slack_id }}> 📬 새로운 PR 리뷰 요청이 도착했습니다!
            👉 <${{ github.event.pull_request.html_url }}|*${{ github.event.pull_request.title }}*>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
